# Generated by Django 3.1.2 on 2021-03-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0004_remove_address_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='email',
            field=models.EmailField(default='null@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='first_name',
            field=models.CharField(default='Test', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='last_name',
            field=models.CharField(default='Last name', max_length=200),
            preserve_default=False,
        ),
    ]
