# Generated by Django 3.1.2 on 2021-05-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='large_image',
            field=models.ImageField(blank=True, help_text='Use a Image with aspect ratio 3/2', null=True, upload_to='customize/recipe/'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='small_image',
            field=models.ImageField(blank=True, help_text='Use a square Image', null=True, upload_to='customize/recipe/'),
        ),
    ]
