# Generated by Django 3.1.2 on 2021-06-09 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0003_homepagebanner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepagebanner',
            options={'verbose_name': 'Homepage Offer Banner', 'verbose_name_plural': 'Homepage Offer Banners'},
        ),
    ]
