# Generated by Django 3.1.2 on 2021-06-09 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0004_auto_20210609_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Handpicked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=250)),
                ('image', models.ImageField(help_text='Upload image with same dimensions as other images on the site', null=True, upload_to='customize/handpicked')),
            ],
        ),
    ]
