# Generated by Django 3.1.2 on 2021-06-09 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_product_handpicked'),
        ('customization', '0005_handpicked'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='handpicked',
            options={'verbose_name': 'Handpicked Product', 'verbose_name_plural': 'Handpicked Products'},
        ),
        migrations.RemoveField(
            model_name='handpicked',
            name='link',
        ),
        migrations.AddField(
            model_name='handpicked',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.product'),
        ),
    ]
