# Generated by Django 3.1.2 on 2021-06-09 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_product_handpicked'),
        ('customization', '0006_auto_20210609_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handpicked',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.product'),
        ),
    ]
