# Generated by Django 3.1.2 on 2021-06-10 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0007_auto_20210609_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Miscellaneous',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Miscellaneous Item',
                'verbose_name_plural': 'Miscellaneous Items',
            },
        ),
    ]
