# Generated by Django 3.1.2 on 2021-06-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0008_miscellaneous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miscellaneous',
            name='name',
            field=models.CharField(help_text='Do not edit this', max_length=100),
        ),
    ]
