# Generated by Django 3.1.2 on 2021-06-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0010_homepagebanner_closemark_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('enable', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='homepagebanner',
            name='closemark_color',
            field=models.CharField(default='#000000', help_text='Use Hexadecimal form for color like #000000 for black and #ffffff for white', max_length=20),
        ),
    ]
