# Generated by Django 3.1.2 on 2021-06-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0011_auto_20210621_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageIngredientIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=1)),
                ('image', models.ImageField(upload_to='customize/ingredientindex/')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('browse_link', models.CharField(max_length=200)),
            ],
        ),
    ]
