# Generated by Django 3.2.4 on 2021-06-25 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0014_alter_homepageingredientindex_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepageingredientindex',
            options={'ordering': (('slide_order', 'name'),), 'verbose_name': 'Homepage Ingredient Index', 'verbose_name_plural': 'Homepage Ingredient Indexes'},
        ),
        migrations.AddField(
            model_name='homepageingredientindex',
            name='slide_order',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
