# Generated by Django 3.2.4 on 2021-06-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0015_auto_20210625_0903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Herobanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_heading', models.TextField()),
                ('side_heading', models.TextField()),
                ('image', models.ImageField(upload_to='customize/herobanner')),
            ],
        ),
        migrations.AlterModelOptions(
            name='homepageingredientindex',
            options={'ordering': ['slide_order', 'name'], 'verbose_name': 'Homepage Ingredient Index', 'verbose_name_plural': 'Homepage Ingredient Indexes'},
        ),
        migrations.AlterField(
            model_name='homepageingredientindex',
            name='slide_order',
            field=models.PositiveIntegerField(help_text='The order in which you want in the website'),
        ),
    ]
