# Generated by Django 3.2.4 on 2021-06-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0016_auto_20210628_1620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='herobanner',
            options={'verbose_name': 'Hero Banner', 'verbose_name_plural': 'Hero Banners'},
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='main_heading',
            field=models.CharField(max_length=500),
        ),
    ]
