# Generated by Django 3.2.4 on 2021-06-29 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0019_herobanner_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='herobanner',
            options={'ordering': ['order', 'main_heading'], 'verbose_name': 'Hero Banner', 'verbose_name_plural': 'Hero Banners'},
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
