# Generated by Django 3.2.4 on 2021-06-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0020_auto_20210629_0826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='large_image',
        ),
        migrations.AddField(
            model_name='recipe',
            name='video',
            field=models.FileField(blank=True, help_text='Use a Image with aspect ratio 3/2', null=True, upload_to='customize/recipe/'),
        ),
    ]
