# Generated by Django 3.2.4 on 2021-07-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0021_auto_20210630_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiprocketCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
