# Generated by Django 3.2.4 on 2021-07-05 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0022_shiprocketcredentials'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shiprocketcredentials',
            options={'ordering': ('-created_at',)},
        ),
    ]
