# Generated by Django 3.2.4 on 2021-07-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0023_alter_shiprocketcredentials_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Font',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('font_size', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=10)),
                ('bold', models.BooleanField(default=False)),
                ('underline', models.BooleanField(default=False)),
                ('italic', models.BooleanField(default=False)),
            ],
        ),
    ]
