# Generated by Django 3.2.4 on 2021-08-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0028_alter_font_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowDoWeDoIt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('video', models.FileField(blank=True, null=True, upload_to='customize/howdowedoit/')),
            ],
        ),
    ]
