# Generated by Django 3.2.4 on 2021-09-16 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0029_howdowedoit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='howdowedoit',
            options={'verbose_name': 'How do we do it', 'verbose_name_plural': 'How Do We Do It'},
        ),
    ]
