# Generated by Django 3.1.2 on 2021-05-30 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20210530_1215'),
        ('analytics', '0003_auto_20210530_1351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderedquantity',
            options={'ordering': ['-ordered_quantity'], 'verbose_name_plural': 'Ordered Quantities'},
        ),
        migrations.AlterField(
            model_name='orderedquantity',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
    ]
