# Generated by Django 3.1.2 on 2021-04-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210405_1351'),
        ('carts', '0004_auto_20210204_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='price',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='quantity_price',
            field=models.ManyToManyField(blank=True, to='products.Quantity_Price'),
        ),
    ]
