# Generated by Django 3.1.2 on 2021-04-07 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210405_1351'),
        ('carts', '0006_cartitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity_price',
            field=models.ManyToManyField(blank=True, null=True, to='products.Quantity_Price'),
        ),
    ]
