# Generated by Django 3.1.2 on 2021-05-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20210527_1833'),
        ('carts', '0007_auto_20210407_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity_price',
            field=models.ManyToManyField(blank=True, to='products.Quantity_Price'),
        ),
    ]
