# Generated by Django 3.1.2 on 2021-06-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20210611_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_code',
            field=models.CharField(help_text='This is the code the user needs to use to get discount', max_length=30),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='description',
            field=models.TextField(blank=True, help_text='This will appear as remarks in the website', null=True),
        ),
    ]
