# Generated by Django 3.2.4 on 2021-07-01 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20210701_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingmethod',
            name='name',
            field=models.CharField(default='Test', help_text="This is for the functionality don't change it", max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True),
        ),
    ]
