# Generated by Django 3.2.4 on 2021-07-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20210701_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='breadth',
            field=models.CharField(blank=True, help_text='The breadth of the item in cms. Must be more than 0.5.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='height',
            field=models.CharField(blank=True, help_text='The height of the item in cms. Must be more than 0.5.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='length',
            field=models.CharField(blank=True, help_text='The length of the item in cms. Must be more than 0.5.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='weight',
            field=models.CharField(blank=True, help_text='The weight of the item in kgs. Must be more than 0.', max_length=200, null=True),
        ),
    ]
