# Generated by Django 3.2.4 on 2021-07-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20210705_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipment_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
