# Generated by Django 3.1.2 on 2021-04-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_flavour'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_price',
            field=models.ManyToManyField(blank=True, null=True, to='products.Quantity_Price'),
        ),
    ]
