# Generated by Django 3.1.2 on 2021-04-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_quantity_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity_price',
            field=models.ManyToManyField(blank=True, to='products.Quantity_Price'),
        ),
    ]
