# Generated by Django 3.1.2 on 2021-04-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='artistic',
            field=models.BooleanField(default=False),
        ),
    ]
