# Generated by Django 3.1.2 on 2021-05-27 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0012_productimage_artistic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quantity_price',
            options={'ordering': ('-price',)},
        ),
        migrations.AddField(
            model_name='product',
            name='avg_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(blank=True, choices=[('1', 'Terrible'), ('2', 'Poor'), ('3', 'Average'), ('4', 'Very Good'), ('5', 'Excellent')], max_length=100, null=True)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
