# Generated by Django 3.1.2 on 2021-05-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_productimage_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('haircare', 'Hair Care'), ('facecare', 'Face Care'), ('bodycare', 'Body Care'), ('gifting', 'Gifting')], default='haircare', max_length=100, null=True),
        ),
    ]
