# Generated by Django 3.2.4 on 2021-06-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_product_handpicked'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
