# Generated by Django 3.2.4 on 2021-06-29 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_productimage_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_multiple_quantity_images',
            field=models.BooleanField(default=False),
        ),
    ]
