# Generated by Django 3.2.4 on 2021-06-30 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_product_has_multiple_quantity_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['artistic', 'main_image', 'quantity']},
        ),
    ]
