# Generated by Django 3.2.4 on 2021-07-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_productimage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(default='Default Sku', max_length=500),
            preserve_default=False,
        ),
    ]
