# Generated by Django 3.2.4 on 2021-07-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_productsku'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsku',
            options={'verbose_name': 'Product Sku', 'verbose_name_plural': 'Products Sku'},
        ),
        migrations.AddField(
            model_name='review',
            name='inappropriate',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
