# Generated by Django 3.2.4 on 2021-08-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_remove_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity_price',
            name='quantity_type',
            field=models.CharField(choices=[('gm', 'GM'), ('ml', 'ML'), ('pcs', 'Pieces')], default='gm', max_length=100),
        ),
    ]
