# Generated by Django 3.2.4 on 2021-08-19 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_alter_quantity_price_quantity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='inappropriate',
            field=models.BooleanField(default=False),
        ),
    ]
